---

plugins:
  - import
  - fp

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  es2020: true

extends:
  - 'airbnb-base'
  - 'plugin:import/recommended'
  - 'plugin:fp/recommended'

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  fp/no-loops: 0
  fp/no-let: 0
  fp/no-mutation: 0
  fp/no-nil: 0
  fp/no-unused-expression: 0
  fp/no-mutating-methods: 0
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
